FROM centos:8
#RUN mkdir workspace

RUN   yum update -y \
 &&   yum install --setopt=tsflags=nodocs -y java-1.8.0-openjdk unzip \
 &&   yum clean all \

#WORKDIR workspace

ADD ./build/libs/lemonade-supply-0.1.0.jar app.jar

EXPOSE 8080

#CMD exec java -jar ${ADDITIONAL_OPTS} app.jar

CMD ["/usr/bin/java", "-jar", "/app.jar"]
